# Generated by Django 5.0.4 on 2024-05-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductShop',
        ),
    ]
